<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLi2ymmh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLi2ymmh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLi2ymmh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLi2ymmh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLi2ymmh\appProdProjectContainer(array(
    'container.build_hash' => 'Li2ymmh',
    'container.build_id' => '54b44819',
    'container.build_time' => 1538059016,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLi2ymmh');
