<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.extractor.document' shared service.

return $this->services['app.extractor.document'] = new \AppBundle\Extractor\DocumentExtractor('https://www.geoportail-urbanisme.gouv.fr', ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
