<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.index.document' shared service.

return $this->services['app.index.document'] = new \AppBundle\Index\DocumentIndex('http://rks1409w113.ign.fr:9200');
