<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.appbundle_command_extract_extractdocumentcommand' shared autowired service.

return $this->services['console.command.appbundle_command_extract_extractdocumentcommand'] = new \AppBundle\Command\Extract\ExtractDocumentCommand();
